### ISSUE TITLE
iostream does not work 

### ISSUE THREAD

**Issue by angryERRORDUDE** [raylib-extras/game-premake#11]
I'm trying to use iostream in this premake but when I try to include it I get 2905 errors. I'm using Visualstudio 2022 and iostream works in my other projects

**Comment by JeffM2501** [comment]
what source file are you using? Are you using a cpp file or the c files from the template?
You can't use iostream from C, since it's a C++ feature.

**Comment by angryERRORDUDE** [comment]
c files from the template ....
......
is there another way to use iostream with the template?
(I wanted to use iostream to store variables permanently).......

**Comment by JeffM2501** [comment]
Yeah, so the template is in C, not C++. You can't use C++ from a C file, that's just how C works. C doesn't know about C++.

You can totally use raylib from C++, you just need to swap the file types over to C++.

You would need to rename the C files in the template to CPP and re-run the batch file for premake. This will configure them for C++.

You will also need to make some small changes to the template C code to make it work in C++, namely any code that puts parenthesis around a class during brace initialization.

So code that looks like this
`(Vector2){ 20, 10 }`
Will have to change to code that looks like this
`Vector2{ 20, 10 }`
Just take out the () from the class. This is one of the subtle differences between C and C++

This issue is not a premake problem, it is the fact that the template is in C not C++

**Comment by JeffM2501** [comment]
Closing, not a premake issue, but simply a misunderstanding of C vs C++ code.
